name: Mean Bean CI

on:
  push:
    branches:
      - main
      - devel
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build UI
        run: |
          cd ui && npm install && npm run build
